[project]
name = "prefect-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dependency-injector>=4.48.2",
    "prefect>=3.5.0",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.11.0",
]
